version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - nerd3dbr-network

  frontend:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    command: sh -c "cd /app && npm run dev -- --host 0.0.0.0"
    networks:
      - nerd3dbr-network

networks:
  nerd3dbr-network:
    driver: bridge

volumes:
  mongodb_data: