export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import Providers from './providers';
import '../App.css';
import '../components/Header.css';
import '../components/Footer.css';
import '../components/Hero.css';
import '../components/About.css';
import '../components/Services.css';
import '../components/Gallery.css';
import '../components/Contact.css';
import Header from '../components/Header';
import Footer from '../components/Footer';

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <body>
        <Providers>
          <Header />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
